#错误和异常

####语法错误  

====
####异常  
* 关键字
  * `raise` 允许程序员强制抛出一个指定的异常
  * `try...except`
  * `pass` 忽略异常
  * `as` 定义异常实例, 如, `except IOError as e`
  * `finally` 定义清理行为, 程序离开`try`后一定被执行
  * `else` 如果`try`语句中没有引发异常, 则执行`else`子句
  * 几点说明
    * `try`后面可跟多个`except`子句, 但至多执行一个分支
    * 一个`except`子句可以在括号中列出多个异常名字, 如: `except (RuntimeError, TypeError, NameError):`
    * 最后一个`except`子句可以省略异常名称, 以作为通配符使用
* `try`语句工作方式
  * 先执行`try`子句(在`try`与`except`关键字之间的部分)
  * 无异常发生, 忽略`except`子句
  * `try`子句执行过程中出现异常, 那么该子句其余部分会被忽略
  * 若异常匹配于`except`后面指定的异常类型, 则执行对应的`except`子句. 完毕后执行`try`语句之后的代码
  * `except`子句中没有与异常匹配的分支, 就会传递到上一级`try`语句中
  * 找不到对应的处理语句, 则成为未处理异常, 终止程序执行, 显示提示信息
* 自定义异常
* `with`预定义清理行为
```
注: 老版本的Python, except语句写作"except Exception, e", Python 2.6以后应写作"except Exception as e"
```

一个有意思的官方文档中出现的例子
注意下raw_input与input
```
#!/usr/bin/env python2
While True:
    try:
         x = int(raw_input("Please enter a number: "))
         break
     except ValueError:
         print "Oops!  That was no valid number.  Try again..."

#!/usr/bin/env python3
while True:
    try:
        x = int(input("Please enter a number: "))
        break
    except ValueError:
    print("Oops!  That was no valid number.  Try again...")
```

Python2中
```
>>> x = input()
2.2
>>> type(x)
<type 'int'>
>>>y = raw_input()
2.2
>>> type(y)
<type 'str'>
>>> int(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '2.2'
```
Python3中
```
>>> x = input()
2.2
>>> type(x)
<type 'str'>
>>> int(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '2.2'
```
总结:  
Python2中存在`input()`与`raw_input()`. 区别: `input()`返回`int`类型变量, `raw_input()`返回`str`类型变量  
Python3中只存在`input()`, 返回`str`类型变量  
`str`类型变量转换成`int`类型变量时, 若有`.`, 会报错  

====
参考资料  
[Python3简体中文文档:8. 错误和异常](http://docs.pythontab.com/python/python3.4/errors.html)

====
```
2015 11.2 晚
```
